version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      DB_URI: mongodb+srv://afsharikasra:vnqmDPWE6ySEc4bZ@cluster0.6m3s24w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
